### ISSUE TITLE
issue handling numeric properties

### ISSUE THREAD

**Issue by gordonmcshane** [skystrife/cpptoml#10]
ex: 

some_property = 500.0 // value->as\<double\>() fine
some_property = 500 // value->as\<double\>() results in crash

while this is correct in toml spec, it puts the onus of type correctness on the toml file creator, which IMO, seems to ask too much of them. perhaps value->as\<double\>() & value->as\<int64_t\>() should work for both integer and float property types?

**Comment by skystrife** [comment]
Hm. I think it would be fine to allow "up conversions" (like from an `int64_t` to a `double`), but not the other way around. I don't think `500.0` should be able to be fetched as an `int64_t`, since there's explicitly a floating point part.

Is that reasonable?

**Comment by gordonmcshane** [comment]
yes. absolutely agree.

**Comment by skystrife** [comment]
Should be fixed now, sorry for the delay.

**Comment by gordonmcshane** [comment]
Thanks!
