### ISSUE TITLE
Difficulty in building a TOML document in code

### ISSUE THREAD

**Issue by dcdillon** [skystrife/cpptoml#14]
There should be some added functions that simplify creating a TOML document in code (and subsequently writing it out).

Specifically there should be an lvalue version of table::insert() for simple items.

Additionally, having to create shared pointers for each type and insert them into tables is...cumbersome.  There are two ways I can see of fixing this:

1) Create correct copy constructors for every cpptoml element and creating a version of the insert function that takes const table&, const array&, const value<T>& etc and makes a copy of each.
2) Creating an element_factory that creates shared pointers to each type.

(1) is cleaner, but (2) will be more efficient.  I don't have a good feeling on which is the right way to go.

Anyhow, once we hash out a design, I'm happy to add this stuff.  Let's discuss.

**Comment by dcdillon** [comment]
Did some more thinking about this and I think the right thing to do (without restructuring a whole bunch of stuff and introducing breaking changes to the API) is to hide all the constructors of base, value, table, table_array, and array.  Then one would create an element_factory that is a friend of all those classes.  This would mean that it would be impossible to declare a cpptoml element on the stack and remove the weirdness that this capability introduces with enable_shared_from_this.

**Comment by skystrife** [comment]
Is `table::insert()` better after 5c81927? There was a bug with `valid_value<T>`.

As for the `shared_ptr` stuff, I'm not sure why this is all that bad:

```cpp
cpptoml::table conf;
auto arr = std::make_shared<cpptoml::array>();
// after your changes are in
arr->push_back(1);
arr->push_back(2);
arr->push_back(3);
conf.insert("arr", arr);
```

The alternative is basically
```cpp
cpptoml::table conf;
auto arr = cpptoml::make_array();
// after your changes are in
arr->push_back(1);
arr->push_back(2);
arr->push_back(3);
conf.insert("arr", arr);
```

which doesn't really seem all that different.

**Comment by dcdillon** [comment]
The fundamental problem that I am trying to address is as follows.

```c++
cpptoml::table t;
t.as_table(); // invalid weak_ptr exception.
```

This pattern follows for all cpptoml classes.

Basically there is zero use for a `cpptoml::value<T>` or any other `cpptoml` type declared on the stack.  They just open up the chance of problems if anyone calls anything that uses `shared_from_this()`.

The best solution I have come up with for this in code is to force the user to create them via a factory that can only create `std::shared_ptr<T>`.

The current implementation allows a user to create objects on the stack and that leads to weird problems.

**Comment by dcdillon** [comment]
The code you show is correct, however, it requires the user to _know_ that they have to call `std::make_shared` to create useful `cpptoml` objects.  With a factory, you simply force the user to do it right.

**Comment by skystrife** [comment]
OK, I'd vote for factory methods then (`make_array`, `make_table`, `make_value`, etc) that are free standing in the `cpptoml` namespace. We can make them friends of their associated class and make the ctors private to prevent user error.

We'll probably want to change the `parse()` function to return a `std::shared_ptr<table>` instead of just a `table`, which will api break... but is probably worth it for consistency. (And since TOML itself isn't yet stable, I'm not too worried about being API stable here either).

**Comment by dcdillon** [comment]
Sounds good.  Once we get the other outstanding PRs done, I'll tackle this.

**Comment by dcdillon** [comment]
Any reason not to close this issue?

**Comment by skystrife** [comment]
Nope, I think this is solved with your changes.
