### ISSUE TITLE
make_xxx() functions broke Windows build.

### ISSUE THREAD

**Issue by barisdemiroz** [skystrife/cpptoml#23]
Hi,
I think the latest `make_xxx()` function additions broke the windows build. I am getting a couple of errors in the following form in VS 2013.

    Error	1	error C2664: 'std::shared_ptr<cpptoml::value<double>> cpptoml::make_value<double>(T &&)' : cannot convert argument 1 from 'int64_t' to 'double &&'	d:\hog-pom\utils\cpptoml.h	364

**Comment by skystrife** [comment]
This will be "fun" to track down since I have no MSVC environment to test in.

What's the call site look like?

**Comment by skystrife** [comment]
Oh I see, the last thing is a line number...

Can you try sticking in a `static_cast<double>` on the referenced line and see what that does?

**Comment by barisdemiroz** [comment]
Thank you! That worked out.

**Comment by dcdillon** [comment]
So should we add a static_cast in there for this?

**Comment by skystrife** [comment]
Yep. Should be fixed as of cb93de8.
