### ISSUE TITLE
Broken Newlines

### ISSUE THREAD

**Issue by foofel** [skystrife/cpptoml#30]
When parsing toml data that is supplied via istringstream that contains "\r\n", the getline behaviour is broken as the \r remains. A fix would probably be http://stackoverflow.com/questions/6089231/getting-std-ifstream-to-handle-lf-cr-and-crlf/6089413#6089413

happens with with visual studio 2015 on win10

**Comment by skystrife** [comment]
Does this only occur with `istringstream`, or can you replicate it with `ifstream` as well?

**Comment by foofel** [comment]
This also happens with ifstream if opened in binary mode, in text mode the line endings are ok. But it is not always feasible, e.g. I am getting already loaded raw data.

**Comment by skystrife** [comment]
This should be fixed now.
