### ISSUE TITLE
Getting uint16_t type value problem.

### ISSUE THREAD

**Issue by korst1k** [skystrife/cpptoml#34]
Hi!
I get static_assertion error:
.../include/cpptoml.h:301: error: static assertion failed: invalid value type
     static_assert(valid_value<T>::value, "invalid value type");
     ^

when i try to compile following code:
```
auto cfg = cpptoml::parse_file(fname);
auto conn = cfg->get_table("connection");
std::string host = *conn->get_as<std::string>("host");
uint16_t port = *conn->get_as<uint16_t>("port");
```

What i am doing wrong?

**Comment by korst1k** [comment]
The snippet compiles only if i change type of port variable to int64_t.
`int64_t x = *conn->get_as<int64_t>("port");`
But i don't need the type of my variable to be as int64_t.
Why only int64_t can be used?

**Comment by korst1k** [comment]
```
struct valid_value
{
    const static bool value
        = std::is_same<T, std::string>::value || std::is_same<T, int64_t>::value
          || std::is_same<T, double>::value || std::is_same<T, bool>::value
          || std::is_same<T, datetime>::value;
};
```
Why only single int64_t?

**Comment by skystrife** [comment]
I'm probably being a bit of a pedant, but [the TOML spec itself only allows for 64-bit signed integers](https://github.com/toml-lang/toml#user-content-integer). So this restriction is reflecting the spec.

We could add some logic to the `get_as<T>()` helpers to allow fetching different integer types, but we'd need to do so carefully to make sure we aren't allowing truncation or overflow to occur.

**Comment by skystrife** [comment]
I think this should just work now, assuming the value that you're fetching is indeed within the range fo the type you request to fetch it as. Internally, everything is still stored as `int64_t` to adhere to the spec.

**Comment by hosaka** [comment]
@skystrife 
Getting an array of uint32_t doesn't work for me:
```
auto pins = config->get_array_of<uint32_t>("pins");
```
Fails with compile error:
```
/usr/local/include/cpptoml.h:619:19: error: static assertion failed: invalid value type
     static_assert(valid_value<T>::value, "invalid value type");
```

Are there additional changes required for array handling?
