### ISSUE TITLE
Any reason why the two test cases failing aren't an issue?

### ISSUE THREAD

**Issue by igor-krawczuk** [skystrife/cpptoml#36]
Is there a known design/functionality complication why those can't be fixed? Or are they simply that prominent to warn people and otherwise are simply open for me to take a swing at if I have time?

**Comment by skystrife** [comment]
> Is there a known design/functionality complication why those can't be fixed?

No, I just haven't bothered with it. C++ doesn't make dealing with Unicode very pleasant, and people have [differing opinions on how unicode strings should be stored in memory](http://utf8everywhere.org/).


> Or are they simply that prominent to warn people

This is the reason, yes.

> and otherwise are simply open for me to take a swing at if I have time?

Go right ahead. :smile: I'd recommend storing the strings as utf8 inside `std::string` as this likely requires the least work and brings in the least dependencies. People can convert from utf8 at boundary points like mentioned in the above article.

**Comment by ishitatsuyuki** [comment]
Since TOML file content is specified to be UTF-8, isn't it ideal to convert the escape code to UTF-8? A fully functional library is also important, rather than conventions.

**Comment by skystrife** [comment]
This is what I was trying to say above: ideally the patch to fix this issue would store utf8 inside `std::string`.
