### ISSUE TITLE
MSVC++ 14.0 Hidden Declaration Warning

### ISSUE THREAD

**Issue by invexed** [skystrife/cpptoml#37]
Sorry to be rather pedantic, but the Visual C++ compiler emits the following warning for the re-declaration of 'v' in the `void base::accept(Visitor&&, Args&&...)` template function between lines 2247-2263:

_warning C4456: declaration of 'v' hides previous local declaration_

Is there a reason why the code is structured in this way?

Thanks!

**Comment by skystrife** [comment]
No, I believe you can safely change the variable names in each of the if branches there. Patches welcome!

**Comment by invexed** [comment]
Sorry, I only just got round to doing it. Thanks for the great lib though!.
