### ISSUE TITLE
Redundant "toml" prefix.

### ISSUE THREAD

**Issue by vadz** [skystrife/cpptoml#4]
It is somewhat annoying to write `cpptoml::toml_group` and so on. Why should "toml" be repeated? IMHO the classes should be renamed so that we could just use `cpptoml::group`.

**Comment by skystrife** [comment]
I agree. I think they were only this way because I didn't put a namespace around it initially when writing it the first time...

This is fixed with the latest flurry of commits to support TOML v0.4.0.
