### ISSUE TITLE
Please Post New Release

### ISSUE THREAD

**Issue by qbradq** [skystrife/cpptoml#42]
I am working on adding cpptoml to the [Hunter](https://github.com/ruslo/hunter) package management system. For that to work well it requires a release version that includes a CMakeLists.txt that includes an install target and CMake package configuration. The latest release package (0.4.0) lacks this, yet I see that HEAD does. Can you make a release for this?

**Comment by ghisvail** [comment]
+1 for Debian / Ubuntu packages

**Comment by MonsieurNicolas** [comment]
Is there a list of issues we can help with in order to land a new release? I also need to pickup a more recent snapshot and would rather pick up an official release than an arbitrary commit in current master

**Comment by vinipsmaker2** [comment]
Any news on this?

**Comment by skystrife** [comment]
I guess my use of tags is confusing. So far, I have just been tagging the first commit where compliance with a certain TOML spec version was reached. This is probably not "correct" given how GitHub likes to interpret tags as "releases"...

I suppose I can start to tag "releases" here, though my personal recommendation is just to always follow the `master` branch.

**Comment by skystrife** [comment]
I've switched to using tags as "releases" to appease GitHub.
