### ISSUE TITLE
You must undef max and min when including windows.h

### ISSUE THREAD

**Issue by lodi-g** [skystrife/cpptoml#43]
Hi,

Not really an issue but I thought you might want to be aware that when using the windows api, you must use the following code:
```cpp
#include <windows.h>
#undef max
#undef min
```

If you don't, it won't compile when using cpptoml and will throw warning when not using it.

Thanks.

**Comment by oblitum** [comment]
@lodi-g to avoid these kind of issues it's the programmer that should `#define NOMINMAX` before including `windows.h`. This flag is accepted by Windows headers so that they don't define those C++ incompatible macros. There's no issue in cpptoml regarding that, this is a Windows header problem.

**Comment by lodi-g** [comment]
You're right, I just thought it'd be worth adding it to the README.

**Comment by geckoo1337** [comment]
Or you can simply wrap your std::min/max in brackets so as to avoid conflict with the macro inside the header windows.h 👍
