### ISSUE TITLE
parse error report！

### ISSUE THREAD

**Issue by kaocs** [skystrife/cpptoml#48]
hi  
   I  use  the master version to test  parse this toml :     https://github.com/toml-lang/toml/blob/master/examples/example-v0.4.0.toml   
Error is : Failed to parse ../toml-master/examples/example-v0.4.0.toml: Malformed number (out of range: stod) at line 152
toml v0.4.0 is supported, ok?

**Comment by skystrife** [comment]
The example document is invalid. See https://github.com/toml-lang/toml/issues/377.
