### ISSUE TITLE
GCC Parse Error

### ISSUE THREAD

**Issue by invexed** [skystrife/cpptoml#50]
I've recently moved from Windows to Fedora, and my code that used to run OK with MSVC now causes
`Exception caught: config file parse error
'---did you forget a '#'? at line 2cter '` when using g++ 6.3.1 (it still compiles cleanly though). The fact that the error message doesn't print correctly at the end is a little strange as well.

At first I thought it could be due to the different line endings between Windows and UNIX, but I re-wrote the config file in Fedora and the problem persists. I've attached the file in question; [config.zip](https://github.com/skystrife/cpptoml/files/1034323/config.zip)

**Comment by skystrife** [comment]
Does the latest commit fix things for you? I suspect line ending shenanigans.

**Comment by invexed** [comment]
There's something weird going on in my environment. After updating last night the problem magically disappeared; I can no longer reproduce the issue even with the old library version.

Thanks for the quick patch though. I might as well close this now that everything seems to be working.
