### ISSUE TITLE
it is a bug here?

### ISSUE THREAD

**Issue by nomadfighter** [skystrife/cpptoml#58]
cpptoml.h  @ line 1474
`template <>`
`inline typename array_of_trait<array>::return_type`
`table::get_qualified_array_of<array>(const std::string& key) const`
`{`
    `if (auto v = get_array(key))   // why not get_array_qualified?`
    `......` 
`}`

**Comment by skystrife** [comment]
Yep, that looks like a copy/paste error. If you issue a PR for that I can merge it in to give you credit for the fix.
