### ISSUE TITLE
will it compile with noexcept nothrow?

### ISSUE THREAD

**Issue by Kulak** [skystrife/cpptoml#60]
I have environment that does not permit exceptions.  I'd like to use your library, but I will need no exceptions.  

As its stands I think the library uses exceptions and that means that I am better off with C based TOML library, unless you tell me that cpptoml throws in so few cases I can adopt the library.

Thank you

**Comment by daskol** [comment]
This is crucial issue for me too.

**Comment by skystrife** [comment]
cpptoml uses exceptions.
