### ISSUE TITLE
Cannot parse nested table arrays

### ISSUE THREAD

**Issue by skakri** [skystrife/cpptoml#61]
Hi, using

```
[services]
modules = [
    "mdns",
]

    [services.trigger]
    # Possible options: "udp", "flic"
    mode = "udp"

        [services.trigger.udp]
        port = 8875

        [services.trigger.flic]
        latency = "NormalLatency"
        uuids = [
            "aa:bb:cc:dd:ee:ff",
            "11:22:33:44:55:66",
        ]
```

```
// Works:
auto services_t = file_conf->get_table("services");
for (const auto &val : *services_t->get_array_of<std::string>("modules")) {
    services.modules.emplace_back(val); // works
}

// auto trigger_t = services_t->get_table("trigger");
// auto flic_t = trigger_t->get_table("flic");

// Doesn't work:
auto flic_t = file_conf->get_table_qualified("services.trigger.flic");
for (const auto &val : *flic_t->get_array_of<std::string>("uuids")) {
    services.trigger.flic.uuids.emplace_back(val); // Cannot access memory at address 0x29
}
```
Am I missing something?

**Comment by skakri** [comment]
OK, it's not related to nesting level – it works in the first level only because there is only one value – it crashes only with multiple values – in *first* iteration.

```
[services_trigger_flic]
latency = "NormalLatency"
uuids = ["a", "b", "c", "d"]
```

```
auto flic_t = file_conf->get_table("services_trigger_flic");

int i = 0;
for (const auto &val : *flic_t->get_array_of<std::string>("uuids")) {
    if (i > 0)
        services.trigger.flic.uuids.emplace_back(val);
    i++;
}

// Will print out b c d
for (auto v : services.trigger.flic.uuids) {
    std::cout << v << std::endl;
}
```

**Comment by skakri** [comment]
Also it spews out malformed data with `"aa:bb:c:dd:ee:ff"` string. I don't know the ins-and-outs of cpptoml, but could it be that it tries to parse it as a date?

**Comment by skakri** [comment]
Ok, if I extract declaration out of `for` loop then it works:

```
const auto values = *flic_t->get_array_of<std::string>("uuids");
for (auto val : values) {
    std::cout << val << std::endl;
}
```

**Comment by skystrife** [comment]
I think you're being bit by the fact that [range-for does not extend the lifetime of all but the last temporary](https://stackoverflow.com/questions/40954539/why-does-using-a-temporary-object-in-the-range-based-for-initializer-result-in-a). So in this case it's extending the lifetime of the `const std::vector<std::string>&` that is returned from `option<std::vector<std::string>>::operator*`, but not the actual `option<std::vector<string>>` itself. The underlying vector, therefore, is destroyed and the range-for loop accesses freed memory.

Hoisting the `option<std::vector<std::string>>` outside of the loop is the best thing to do here, I think. I would typically write something like this as

```cpp
auto uuids = flic_t->get_array_of<std::string>("uuids");
if (!uuids)
{
    // do something if "uuids" key is not present, maybe error out?
}
for (const auto& val : *uuids)
{
    // do something with val
}
```
