### ISSUE TITLE
Doesn't parse Hex Values

### ISSUE THREAD

**Issue by jayache80** [skystrife/cpptoml#64]
It doesn't parse hex values. It fails with "Unidentified trailing character 'x'---did you forgot a '#'?"

Testcase:
```
# test.toml:
TestHex = 0x55
```

```
// main.cpp
    auto config = cpptoml::parse_file("uc2ui.toml");
    auto cfgTestHex = config->get_as<int64_t>("TestHex");
```

Compiling with visual studio 2015 32-bit, within a QT 5.10.0 framework

**Comment by siteseer** [comment]
Same problem
Eclipse CDT with GNU C++
Would love to see a fix for this

**Comment by skystrife** [comment]
Hex values are not allowed in [the v0.4.0 spec](https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md), which cpptoml was written to follow.

However, I would be willing to accept any patch that remedies this as the behavior will change upon the release of TOML v1.0.0.
